BeginTestCase  "Free RDP: Get RemoteClipboard Unicode Test"

//CRD: ADT-867

set maxWait = 5 
Run "ClipboardTest/RemoteClipboardUnicodeTest"

set testData = "Chinese"
Run "ClipboardTest/RemoteClipboardUnicodeTest".verify_result maxWait, testData

set testData = "German"
Run "ClipboardTest/RemoteClipboardUnicodeTest".verify_result maxWait, testData

set testData = "Japanese"
Run "ClipboardTest/RemoteClipboardUnicodeTest".verify_result maxWait, testData

set testData = "Korean"
Run "ClipboardTest/RemoteClipboardUnicodeTest".verify_result maxWait, testData

set testData = "Hebrew"
Run "ClipboardTest/RemoteClipboardUnicodeTest".verify_result maxWait, testData

Helper.clearNotePadText maxWait
run "Helpers/cleanUpWindows".cleanWindows maxWait

EndTestCase "Free RDP: Get RemoteClipboard Unicode Test"